### PR TITLE
Use Docker for deploying and running NCN26010 user-space driver

### PR DESCRIPTION
**Pull request by aentinger**

### CODE REVIEW

**Comment by aentinger** [comment]
Hi @pavel-kirienko :coffee: :wave: 

Can you please take a look at the shell scripts `docker-build.sh`/`docker-run.sh` if there are improvements to be made/terrible errors to be corrected?

**Comment by aentinger** [comment]
Hi @wuehr1999 :coffee: :wave:

Can you please take a look at the Dockerfile and associated build/run files if there are any major "Docker" no-nos?

Is there a better was to provide sysfs within the Docker container without using `--privileged`?

**Comment by wuehr1999** [comment]
Hi @aentinger,
LGTM. Usually mounting the sysfs with ```-v /sys:/sys``` should work.

**Comment by aentinger** [comment]
> Hi @aentinger, LGTM. Usually mounting the sysfs with `-v /sys:/sys` should work.

Without `--priviliged` sysfs is mounted read-only -.-

```bash
/sys/class/gpio # echo out > gpio85/direction 
/bin/sh: can't create gpio85/direction: Read-only file system
```

**Pull request merged**
